using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skynet.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class NetworkVariableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allFields = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is FieldDeclarationSyntax f && f.AttributeLists.Count > 0,
                transform: static (ctx, _) => ExtractField(ctx))
            .Where(static v => v is not null)
            .Select(static (v, _) => v!.Value)
            .Collect();

        var allCallbacks = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                transform: static (ctx, _) => ExtractOnChangeCallback(ctx))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!.Value)
            .Collect();

        var classes = allFields
            .Combine(allCallbacks)
            .Select(static (tuple, _) =>
            {
                var (fields, callbacks) = tuple;

                var fieldsByClass = fields.GroupBy(f => f.ContainingTypeFullName)
                    .ToDictionary(g => g.Key, g => g.ToImmutableArray());

                var callbacksByClass = callbacks.GroupBy(c => c.ContainingTypeFullName)
                    .ToDictionary(g => g.Key, g => g.ToImmutableArray());

                return fieldsByClass.Select(kv => new NetworkVariableClassInfo(
                    containingNamespace: kv.Value[0].ContainingNamespace,
                    className: kv.Value[0].ClassName,
                    containingTypeFullName: kv.Key,
                    variables: kv.Value,
                    callbacks: callbacksByClass.TryGetValue(kv.Key, out var cs)
                        ? cs
                        : ImmutableArray<OnChangeCallbackInfo>.Empty
                )).ToImmutableArray();
            });

        context.RegisterSourceOutput(classes, static (ctx, classInfos) =>
        {
            foreach (var classInfo in classInfos)
                EmitClassFile(ctx, classInfo);
        });
    }

    private static void EmitClassFile(SourceProductionContext ctx, NetworkVariableClassInfo classInfo)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable disable");

        bool hasNamespace = !string.IsNullOrEmpty(classInfo.ContainingNamespace);

        if (hasNamespace) sb.Append("namespace ").Append(classInfo.ContainingNamespace).AppendLine("\n{");
        string indent = hasNamespace ? "    " : "";

        sb.Append(indent).Append("partial class ").AppendLine(classInfo.ClassName);
        sb.Append(indent).AppendLine("{");

        for (int i = 0; i < classInfo.Variables.Length; i++)
        {
            var v = classInfo.Variables[i];
            int hash = Fnv1a(v.FieldName);

            sb.Append(indent).Append("    private const int __VarId_").Append(v.FieldName)
                .Append(" = unchecked((int)0x").Append(((uint)hash).ToString("X8")).Append(");")
                .Append("    // FNV-1a(\"").Append(v.FieldName).AppendLine("\")");

            sb.Append(indent).Append("    private ").Append(v.TypeDisplay)
                .Append(" __lastSynced_").Append(v.FieldName).AppendLine(";");
        }

        sb.AppendLine();

        foreach (var v in classInfo.Variables)
        {
            sb.Append(indent).Append("    public event global::System.Action<")
                .Append(v.TypeDisplay).Append(", ").Append(v.TypeDisplay)
                .Append("> On").Append(v.FieldName).AppendLine("Changed;");
        }

        sb.AppendLine();

        var ownerTcp = new List<NetworkVariableInfo>();
        var ownerUdp = new List<NetworkVariableInfo>();
        var serverTcp = new List<NetworkVariableInfo>();
        var serverUdp = new List<NetworkVariableInfo>();

        foreach (var v in classInfo.Variables)
        {
            bool isOwner = v.Authority == Authority.Owner;
            bool isTcp = v.Protocol == NetProtocolType.Tcp;
    
            if (isOwner && isTcp) ownerTcp.Add(v);
            else if (isOwner) ownerUdp.Add(v);
            else if (isTcp) serverTcp.Add(v);
            else serverUdp.Add(v);
        }

        sb.Append(indent).AppendLine("    protected override void CollectDirtyVariables(" +
                                     "global::System.Collections.Generic.List<global::Skynet.Data.NetworkVariables.VariableDelta> tcpOutput, " +
                                     "global::System.Collections.Generic.List<global::Skynet.Data.NetworkVariables.VariableDelta> udpOutput)");
        sb.Append(indent).AppendLine("    {");

        if (ownerTcp.Count > 0 || ownerUdp.Count > 0)
        {
            sb.Append(indent).AppendLine("        if (IsOwner)");
            sb.Append(indent).AppendLine("        {");
            foreach (var v in ownerTcp) EmitCollectForField(sb, indent + "        ", v, "tcpOutput");
            foreach (var v in ownerUdp) EmitCollectForField(sb, indent + "        ", v, "udpOutput");
            sb.Append(indent).AppendLine("        }");
        }
        if (serverTcp.Count > 0 || serverUdp.Count > 0)
        {
            sb.Append(indent).AppendLine("        if (IsServer)");
            sb.Append(indent).AppendLine("        {");
            foreach (var v in serverTcp) EmitCollectForField(sb, indent + "        ", v, "tcpOutput");
            foreach (var v in serverUdp) EmitCollectForField(sb, indent + "        ", v, "udpOutput");
            sb.Append(indent).AppendLine("        }");
        }

        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("    protected override void ApplyVariableDelta(int index, byte[] payload)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        switch (index)");
        sb.Append(indent).AppendLine("        {");

        foreach (var v in classInfo.Variables)
        {
            string callbackMethod = null;
            foreach (var cb in classInfo.Callbacks)
            {
                if (cb.FieldName == v.FieldName)
                {
                    callbackMethod = cb.MethodName;
                    break;
                }
            }

            sb.Append(indent).Append("            case __VarId_").Append(v.FieldName).AppendLine(":");
            sb.Append(indent).AppendLine("            {");
            sb.Append(indent).Append("                var __old_").Append(v.FieldName)
                .Append(" = ").Append(v.FieldName).AppendLine(";");
            sb.Append(indent).Append("                ").Append(v.FieldName)
                .Append(" = global::MessagePack.MessagePackSerializer.Deserialize<")
                .Append(v.TypeDisplay).AppendLine(">(payload);");
            sb.Append(indent).Append("                On").Append(v.FieldName)
                .Append("Changed?.Invoke(__old_").Append(v.FieldName).Append(", ")
                .Append(v.FieldName).AppendLine(");");
            if (callbackMethod != null)
            {
                sb.Append(indent).Append("                ").Append(callbackMethod)
                    .Append("(__old_").Append(v.FieldName).Append(", ")
                    .Append(v.FieldName).AppendLine(");");
            }

            sb.Append(indent).AppendLine("                break;");
            sb.Append(indent).AppendLine("            }");
        }

        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("}");
        if (hasNamespace) sb.AppendLine("}");

        string fileName = "Skynet.NetworkVariables." + classInfo.ContainingTypeFullName + ".g.cs";
        ctx.AddSource(fileName, sb.ToString());
    }

    private static void EmitCollectForField(StringBuilder sb, string extraIndent, NetworkVariableInfo v, string outputName)
    {
        sb.Append(extraIndent).Append("    if (!global::System.Collections.Generic.EqualityComparer<")
            .Append(v.TypeDisplay).Append(">.Default.Equals(").Append(v.FieldName).Append(", __lastSynced_")
            .Append(v.FieldName).AppendLine("))");
        sb.Append(extraIndent).AppendLine("    {");
        sb.Append(extraIndent).Append("        ").Append(outputName)   // ← используем параметр
            .Append(".Add(new global::Skynet.Data.NetworkVariables.VariableDelta(__VarId_")
            .Append(v.FieldName).Append(", global::MessagePack.MessagePackSerializer.Serialize(")
            .Append(v.FieldName).AppendLine(")));");
        sb.Append(extraIndent).Append("        __lastSynced_").Append(v.FieldName)
            .Append(" = ").Append(v.FieldName).AppendLine(";");
        sb.Append(extraIndent).AppendLine("    }");
    }

    private static NetworkVariableInfo? ExtractField(GeneratorSyntaxContext ctx)
    {
        var fieldSyntax = (FieldDeclarationSyntax)ctx.Node;

        bool hasAttr = false;
        foreach (var list in fieldSyntax.AttributeLists)
        {
            foreach (var attr in list.Attributes)
            {
                string name = attr.Name.ToString();
                string simpleName = name.Contains(".") ? name.Substring(name.LastIndexOf('.') + 1) : name;
                if (simpleName.EndsWith("Attribute"))
                    simpleName = simpleName.Substring(0, simpleName.Length - "Attribute".Length);
                if (simpleName == "SyncVar")
                {
                    hasAttr = true;
                    break;
                }
            }

            if (hasAttr) break;
        }

        if (!hasAttr) return null;

        var variable = fieldSyntax.Declaration.Variables[0];
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(variable) as IFieldSymbol;
        if (symbol is null) return null;

        Authority authority = Authority.Auto;
        NetProtocolType protocol = NetProtocolType.Tcp;
        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName != "Skynet.Data.Attributes.SyncVarAttribute") continue;

            var args = attr.ConstructorArguments;
            if (args.Length > 0 && args[0].Value is int authValue)
                authority = (Authority)authValue;
            if (args.Length > 1 && args[1].Value is int protoValue)
                protocol = protoValue == 1 ? NetProtocolType.Udp : NetProtocolType.Tcp;
            break;
        }

        var containingType = symbol.ContainingType;
        if (containingType is null) return null;

        var noGlobalFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted);

        bool inheritsService = false;
        for (var t = containingType.BaseType; t is not null; t = t.BaseType)
        {
            var name = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(
                SymbolDisplayGlobalNamespaceStyle.Omitted));
            if (name == "Skynet.NetworkComponents.NetworkService")
            {
                inheritsService = true;
                break;
            }
        }

        if (authority == Authority.Auto)
            authority = inheritsService ? Authority.Server : Authority.Owner;

        if (inheritsService && authority == Authority.Owner)
            authority = Authority.Server;

        return new NetworkVariableInfo(
            fieldName: symbol.Name,
            typeDisplay: symbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            containingNamespace: containingType.ContainingNamespace.IsGlobalNamespace
                ? ""
                : containingType.ContainingNamespace.ToDisplayString(),
            className: containingType.Name,
            containingTypeFullName: containingType.ToDisplayString(noGlobalFormat),
            authority: authority,
            protocol: protocol
        );
    }

    private static OnChangeCallbackInfo? ExtractOnChangeCallback(GeneratorSyntaxContext ctx)
    {
        var methodSyntax = (MethodDeclarationSyntax)ctx.Node;

        bool hasAttr = false;
        foreach (var list in methodSyntax.AttributeLists)
        {
            foreach (var attr in list.Attributes)
            {
                string name = attr.Name.ToString();
                string simple = name.Contains(".") ? name.Substring(name.LastIndexOf('.') + 1) : name;
                if (simple.EndsWith("Attribute"))
                    simple = simple.Substring(0, simple.Length - "Attribute".Length);
                if (simple == "OnChange")
                {
                    hasAttr = true;
                    break;
                }
            }

            if (hasAttr) break;
        }

        if (!hasAttr) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;
        if (symbol is null) return null;

        string fieldName = null;
        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName != "Skynet.Data.Attributes.OnChangeAttribute") continue;
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string s)
                fieldName = s;
            break;
        }

        if (fieldName == null) return null;

        var containingType = symbol.ContainingType;
        if (containingType is null) return null;

        var noGlobalFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(
            SymbolDisplayGlobalNamespaceStyle.Omitted);

        return new OnChangeCallbackInfo(
            containingTypeFullName: containingType.ToDisplayString(noGlobalFormat),
            fieldName: fieldName,
            methodName: symbol.Name);
    }

    private readonly struct NetworkVariableInfo
    {
        public string FieldName { get; }
        public string TypeDisplay { get; }
        public string ContainingNamespace { get; }
        public string ClassName { get; }
        public string ContainingTypeFullName { get; }
        public Authority Authority { get; }
        public NetProtocolType Protocol { get; }

        public NetworkVariableInfo(string fieldName, string typeDisplay, string containingNamespace,
            string className, string containingTypeFullName, Authority authority, NetProtocolType protocol)
        {
            FieldName = fieldName;
            TypeDisplay = typeDisplay;
            ContainingNamespace = containingNamespace;
            ClassName = className;
            ContainingTypeFullName = containingTypeFullName;
            Authority = authority;
            Protocol = protocol;
        }
    }

    private sealed class NetworkVariableClassInfo
    {
        public string ContainingNamespace { get; }
        public string ClassName { get; }
        public string ContainingTypeFullName { get; }
        public ImmutableArray<NetworkVariableInfo> Variables { get; }
        public ImmutableArray<OnChangeCallbackInfo> Callbacks { get; }

        public NetworkVariableClassInfo(string containingNamespace, string className, string containingTypeFullName,
            ImmutableArray<NetworkVariableInfo> variables, ImmutableArray<OnChangeCallbackInfo> callbacks)
        {
            ContainingNamespace = containingNamespace;
            ClassName = className;
            ContainingTypeFullName = containingTypeFullName;
            Variables = variables;
            Callbacks = callbacks;
        }
    }

    private readonly struct OnChangeCallbackInfo
    {
        public string ContainingTypeFullName { get; }
        public string FieldName { get; }
        public string MethodName { get; }

        public OnChangeCallbackInfo(string containingTypeFullName, string fieldName, string methodName)
        {
            ContainingTypeFullName = containingTypeFullName;
            FieldName = fieldName;
            MethodName = methodName;
        }
    }

    private enum Authority
    {
        Auto = 0,
        Owner = 1,
        Server = 2
    }

    private enum NetProtocolType
    {
        Tcp = 0,
        Udp = 1
    }

    private static int Fnv1a(string s)
    {
        if (s == null) return 0;
        unchecked
        {
            int hash = (int)2166136261;
            for (int i = 0; i < s.Length; i++)
            {
                hash ^= s[i];
                hash *= 16777619;
            }

            return hash;
        }
    }
}