using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skynet.SourceGenerators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class RpcGenerator : IIncrementalGenerator
    {
        private const string HandlePrefix = "Handle";
        private const string SenderIdParamName = "senderId";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Discovery via SyntaxProvider — walks every attribute-decorated method,
            // matches [ServerRpc]/[ClientRpc] by simple name.
            var allMethods = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                    transform: static (ctx, _) => ExtractByScan(ctx))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!.Value)
                .Collect();

            var classes = allMethods
                .Select(static (methods, _) => methods
                    .GroupBy(m => m.ContainingTypeFullName)
                    .Select(g => new RpcClassInfo(
                        containingNamespace: g.First().ContainingNamespace,
                        className: g.First().ClassName,
                        containingTypeFullName: g.Key,
                        methods: g.ToImmutableArray()))
                    .ToImmutableArray());

            context.RegisterSourceOutput(classes, static (ctx, classInfos) =>
            {
                foreach (var classInfo in classInfos)
                    EmitClassFile(ctx, classInfo);
            });

            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource(
                    "Skynet.RpcGenerator.__Marker.g.cs",
                    "// <auto-generated />\n" +
                    "namespace Skynet.__Generated { internal static class Marker { public const string Version = \"0.1.0\"; } }\n");
            });

            // Raw syntax-level scan of every method with any attribute — pure syntax, no semantic model.
            // If this reports 0 in Assembly-CSharp, the syntax provider itself is not visiting Bootstrapper.
            var rawScan = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                    transform: static (ctx, _) =>
                    {
                        var m = (MethodDeclarationSyntax)ctx.Node;
                        var attrs = string.Join(",",
                            m.AttributeLists.SelectMany(l => l.Attributes).Select(a => a.Name.ToString()));
                        return $"{m.Identifier.Text}<{attrs}>";
                    })
                .Collect();

            context.RegisterSourceOutput(rawScan.Combine(context.CompilationProvider), static (ctx, tuple) =>
            {
                var (names, comp) = tuple;
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("// Assembly: " + comp.AssemblyName);
                sb.AppendLine("// Total attributed methods seen: " + names.Length);
                foreach (var n in names) sb.AppendLine("//   " + n);
                ctx.AddSource($"Skynet.RpcGenerator.__RawScan.{comp.AssemblyName}.g.cs", sb.ToString());
            });
        }

        private static RpcMethodInfo? ExtractByScan(GeneratorSyntaxContext ctx)
        {
            var methodSyntax = (MethodDeclarationSyntax)ctx.Node;

            RpcDirection? direction = null;
            foreach (var list in methodSyntax.AttributeLists)
            {
                foreach (var attr in list.Attributes)
                {
                    string attrName = attr.Name.ToString();
                    string simpleName = attrName.Contains(".") ? attrName.Substring(attrName.LastIndexOf('.') + 1) : attrName;
                    if (simpleName.EndsWith("Attribute"))
                        simpleName = simpleName.Substring(0, simpleName.Length - "Attribute".Length);

                    if (simpleName == "ServerRpc") { direction = RpcDirection.Server; break; }
                    if (simpleName == "ClientRpc") { direction = RpcDirection.Client; break; }
                }
                if (direction is not null) break;
            }

            if (direction is null) return null;

            var symbol = ctx.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;
            if (symbol is null) return null;

            AttributeData? matchingAttr = null;
            foreach (var attr in symbol.GetAttributes())
            {
                var name = attr.AttributeClass?.ToDisplayString();
                if (direction == RpcDirection.Server &&
                    (name == "Skynet.Data.Attributes.ServerRpcAttribute" || name == "Skynet.Data.Attributes.ServerRpc"))
                {
                    matchingAttr = attr; break;
                }
                if (direction == RpcDirection.Client &&
                    (name == "Skynet.Data.Attributes.ClientRpcAttribute" || name == "Skynet.Data.Attributes.ClientRpc"))
                {
                    matchingAttr = attr; break;
                }
            }

            var type = symbol.ContainingType;
            if (type is null) return null;

            string protocol = "Tcp";
            RpcTarget target = RpcTarget.All;
            // Default matches the attribute ctor default in Skynet.Data.Attributes.
            HandlerExecution execution = HandlerExecution.MainThread;

            if (matchingAttr is not null)
            {
                var args = matchingAttr.ConstructorArguments;
                if (args.Length > 0 && args[0].Value is int protoValue)
                    protocol = protoValue == 1 ? "Udp" : "Tcp";

                // ServerRpc(protocol, execution)          — args[1] is execution
                // ClientRpc(protocol, target, execution)  — args[1] is target, args[2] is execution
                if (direction == RpcDirection.Server)
                {
                    if (args.Length > 1 && args[1].Value is int serverExecValue)
                        execution = (HandlerExecution)serverExecValue;
                }
                else
                {
                    if (args.Length > 1 && args[1].Value is int targetValue)
                        target = (RpcTarget)targetValue;
                    if (args.Length > 2 && args[2].Value is int clientExecValue)
                        execution = (HandlerExecution)clientExecValue;
                }
            }

            var parameters = ImmutableArray.CreateBuilder<RpcParamInfo>(symbol.Parameters.Length);
            foreach (var p in symbol.Parameters)
            {
                parameters.Add(new RpcParamInfo(
                    name: p.Name,
                    typeDisplay: p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
            }

            // Use a display format WITHOUT the "global::" prefix — that prefix is illegal in filenames
            // (Roslyn AddSource rejects ':') and would drift from the runtime FNV-1a hash we compute
            // over the same string in Skynet.RpcId.
            var noGlobalFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(
                SymbolDisplayGlobalNamespaceStyle.Omitted);

            return new RpcMethodInfo(
                methodName: symbol.Name,
                direction: direction.Value,
                protocol: protocol,
                target: target,
                containingNamespace: type.ContainingNamespace.IsGlobalNamespace
                    ? ""
                    : type.ContainingNamespace.ToDisplayString(),
                className: type.Name,
                containingTypeFullName: type.ToDisplayString(noGlobalFormat),
                parameters: parameters.ToImmutable(),
                execution: execution);
        }

        private static void EmitClassFile(SourceProductionContext ctx, RpcClassInfo classInfo)
        {
            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(classInfo.ContainingNamespace);
            if (hasNamespace)
            {
                sb.Append("namespace ").Append(classInfo.ContainingNamespace).AppendLine();
                sb.AppendLine("{");
            }

            string indent = hasNamespace ? "    " : "";

            // No `: IRpcHandlerProvider` — base NetworkService / NetworkBehaviour already implements it.
            sb.Append(indent).Append("partial class ").Append(classInfo.ClassName).AppendLine();
            sb.Append(indent).AppendLine("{");

            int callerTypeId = Fnv1a(classInfo.ContainingTypeFullName);
            sb.Append(indent).Append("    private const int __CallerTypeId = unchecked((int)0x")
                .Append(((uint)callerTypeId).ToString("X8"))
                .Append("); // FNV-1a(\"").Append(classInfo.ContainingTypeFullName).AppendLine("\")");

            foreach (var m in classInfo.Methods)
            {
                int methodId = Fnv1a(BuildMethodSignatureForHash(classInfo.ContainingTypeFullName, m));
                sb.Append(indent).Append("    private const int __MethodId_").Append(m.MethodName)
                    .Append(" = unchecked((int)0x").Append(((uint)methodId).ToString("X8")).Append(");");
                sb.Append(" // FNV-1a(\"").Append(BuildMethodSignatureForHash(classInfo.ContainingTypeFullName, m)).AppendLine("\")");
            }

            sb.AppendLine();

            // Override the base's virtual RegisterHandlers — installs every RPC handler
            // into the RpcRegistry the base already captured during InitializeRpc.
            sb.Append(indent).AppendLine("    protected override void RegisterHandlers()");
            sb.Append(indent).AppendLine("    {");

            foreach (var m in classInfo.Methods)
            {
                EmitHandlerRegistration(sb, indent + "        ", m);
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();

            // Sender wrappers — reach for the RpcSender the base exposes as a public property.
            foreach (var m in classInfo.Methods)
            {
                EmitSenderWrapper(sb, indent + "    ", m);
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("}");
            if (hasNamespace) sb.AppendLine("}");

            string fileName = "Skynet.Rpc." + classInfo.ContainingTypeFullName + ".g.cs";
            ctx.AddSource(fileName, sb.ToString());
        }

        private static void EmitHandlerRegistration(StringBuilder sb, string indent, in RpcMethodInfo m)
        {
            var payloadParams = GetPayloadParams(m.Parameters);
            bool takesSenderId = m.Parameters.Length > payloadParams.Length;

            sb.Append(indent).AppendLine("RpcRegistry.Register(");
            sb.Append(indent).AppendLine("    __CallerTypeId,");
            sb.Append(indent).AppendLine("    InstanceId,");
            sb.Append(indent).Append("    __MethodId_").Append(m.MethodName).AppendLine(",");
            sb.Append(indent).AppendLine("    (payload, sid) =>");
            sb.Append(indent).AppendLine("    {");

            string call;
            if (payloadParams.Length == 0)
            {
                call = takesSenderId ? $"{m.MethodName}(sid);" : $"{m.MethodName}();";
            }
            else if (payloadParams.Length == 1)
            {
                sb.Append(indent).Append("        var __arg = global::MessagePack.MessagePackSerializer.Deserialize<")
                    .Append(payloadParams[0].TypeDisplay).AppendLine(">(payload);");
                call = takesSenderId
                    ? $"{m.MethodName}(sid, __arg);"
                    : $"{m.MethodName}(__arg);";
            }
            else
            {
                sb.Append(indent).Append("        var __t = global::MessagePack.MessagePackSerializer.Deserialize<(");
                for (int i = 0; i < payloadParams.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(payloadParams[i].TypeDisplay);
                }
                sb.AppendLine(")>(payload);");

                var callBuilder = new StringBuilder();
                callBuilder.Append(m.MethodName).Append("(");
                if (takesSenderId) callBuilder.Append("sid, ");
                for (int i = 0; i < payloadParams.Length; i++)
                {
                    if (i > 0) callBuilder.Append(", ");
                    callBuilder.Append("__t.Item").Append(i + 1);
                }
                callBuilder.Append(");");
                call = callBuilder.ToString();
            }

            sb.Append(indent).Append("        ").AppendLine(call);
            sb.Append(indent).AppendLine("    },");
            sb.Append(indent).Append("    global::Skynet.RpcSystem.HandlerExecution.")
                .Append(m.Execution)
                .AppendLine(");");
        }

        private static void EmitSenderWrapper(StringBuilder sb, string indent, in RpcMethodInfo m)
        {
            string senderMethodName = StripHandlePrefix(m.MethodName);

            // One wrapper per handler. The [ClientRpc(target: ...)] value picks its shape:
            //   All    -> Xxx(...)              broadcast to every client
            //   Client -> Xxx(int clientId, ...) unicast to a specific client
            // For [ServerRpc] the target is always "the server", no choice.
            WrapperKind kind = m.Direction == RpcDirection.Server
                ? WrapperKind.Server
                : (m.Target == RpcTarget.Client ? WrapperKind.ClientTargeted : WrapperKind.ClientBroadcast);

            EmitOneWrapper(sb, indent, m, senderMethodName, kind);
        }

        private enum WrapperKind { Server, ClientBroadcast, ClientTargeted }

        private static void EmitOneWrapper(StringBuilder sb, string indent, in RpcMethodInfo m,
            string senderMethodName, WrapperKind kind)
        {
            var payloadParams = GetPayloadParams(m.Parameters);
            bool targeted = kind == WrapperKind.ClientTargeted;

            // Signature: for targeted, prepend `int clientId`; otherwise just the payload params.
            sb.Append(indent).Append("public void ").Append(senderMethodName).Append("(");
            if (targeted) sb.Append("int clientId");
            for (int i = 0; i < payloadParams.Length; i++)
            {
                if (i > 0 || targeted) sb.Append(", ");
                sb.Append(payloadParams[i].TypeDisplay).Append(" ").Append(payloadParams[i].Name);
            }
            sb.AppendLine(")");
            sb.Append(indent).AppendLine("{");

            // Payload serialization (same for all wrapper kinds).
            if (payloadParams.Length == 0)
            {
                sb.Append(indent).AppendLine("    var __payload = global::System.Array.Empty<byte>();");
            }
            else if (payloadParams.Length == 1)
            {
                sb.Append(indent).Append("    var __payload = global::MessagePack.MessagePackSerializer.Serialize(")
                    .Append(payloadParams[0].Name).AppendLine(");");
            }
            else
            {
                sb.Append(indent).Append("    var __payload = global::MessagePack.MessagePackSerializer.Serialize((");
                for (int i = 0; i < payloadParams.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(payloadParams[i].Name);
                }
                sb.AppendLine("));");
            }

            // Dispatch call — direction/target picks which IRpcSender method we hit.
            string sendCall;
            string prefixArgs;
            switch (kind)
            {
                case WrapperKind.Server:
                    sendCall = "RpcSender.SendToServer";
                    prefixArgs = "";
                    break;
                case WrapperKind.ClientBroadcast:
                    sendCall = "RpcSender.BroadcastToClients";
                    prefixArgs = "";
                    break;
                case WrapperKind.ClientTargeted:
                    sendCall = "RpcSender.SendToClient";
                    prefixArgs = "clientId, ";
                    break;
                default:
                    throw new System.InvalidOperationException("Unknown WrapperKind");
            }

            sb.Append(indent).Append("    ").Append(sendCall).Append("(").Append(prefixArgs)
                .Append("__CallerTypeId, InstanceId, __MethodId_").Append(m.MethodName)
                .Append(", __payload, global::Skynet.RpcSystem.ProcessorsData.NetProtocolType.")
                .Append(m.Protocol).AppendLine(");");
            sb.Append(indent).AppendLine("}");
        }

        private static string StripHandlePrefix(string methodName) =>
            methodName.StartsWith(HandlePrefix) && methodName.Length > HandlePrefix.Length
                ? methodName.Substring(HandlePrefix.Length)
                : methodName + "Rpc";

        private static ImmutableArray<RpcParamInfo> GetPayloadParams(ImmutableArray<RpcParamInfo> all)
        {
            if (all.Length == 0) return all;
            var first = all[0];
            if (first.Name == SenderIdParamName && (first.TypeDisplay == "int" || first.TypeDisplay == "global::System.Int32"))
                return all.RemoveAt(0);
            return all;
        }

        private static string BuildMethodSignatureForHash(string containingTypeFullName, in RpcMethodInfo m)
        {
            var sb = new StringBuilder();
            sb.Append(containingTypeFullName).Append('.').Append(m.MethodName).Append('(');
            for (int i = 0; i < m.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append(m.Parameters[i].TypeDisplay);
            }
            sb.Append(')');
            return sb.ToString();
        }

        private static int Fnv1a(string s)
        {
            if (s == null) return 0;
            unchecked
            {
                int hash = (int)2166136261;
                for (int i = 0; i < s.Length; i++)
                {
                    hash ^= s[i];
                    hash *= 16777619;
                }
                return hash;
            }
        }

        private enum RpcDirection { Server, Client }

        // Mirrors Skynet.RpcSystem.RpcTarget — duplicated because the generator can't reference Core.
        private enum RpcTarget { All = 0, Client = 1 }

        // Mirrors Skynet.RpcSystem.HandlerExecution — duplicated for the same reason.
        private enum HandlerExecution { Immediate = 0, MainThread = 1 }

        private readonly struct RpcMethodInfo
        {
            public string MethodName { get; }
            public RpcDirection Direction { get; }
            public string Protocol { get; }
            public RpcTarget Target { get; }
            public string ContainingNamespace { get; }
            public string ClassName { get; }
            public string ContainingTypeFullName { get; }
            public ImmutableArray<RpcParamInfo> Parameters { get; }
            public HandlerExecution Execution { get; }

            public RpcMethodInfo(string methodName, RpcDirection direction, string protocol, RpcTarget target,
                string containingNamespace, string className, string containingTypeFullName,
                ImmutableArray<RpcParamInfo> parameters, HandlerExecution execution)
            {
                MethodName = methodName;
                Direction = direction;
                Protocol = protocol;
                Target = target;
                ContainingNamespace = containingNamespace;
                ClassName = className;
                ContainingTypeFullName = containingTypeFullName;
                Parameters = parameters;
                Execution = execution;
            }
        }

        private readonly struct RpcParamInfo
        {
            public string Name { get; }
            public string TypeDisplay { get; }

            public RpcParamInfo(string name, string typeDisplay)
            {
                Name = name;
                TypeDisplay = typeDisplay;
            }
        }

        private sealed class RpcClassInfo
        {
            public string ContainingNamespace { get; }
            public string ClassName { get; }
            public string ContainingTypeFullName { get; }
            public ImmutableArray<RpcMethodInfo> Methods { get; }

            public RpcClassInfo(string containingNamespace, string className,
                string containingTypeFullName, ImmutableArray<RpcMethodInfo> methods)
            {
                ContainingNamespace = containingNamespace;
                ClassName = className;
                ContainingTypeFullName = containingTypeFullName;
                Methods = methods;
            }
        }
    }
}
